/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unimontes.ccet.dcc.pg1.view;

import br.unimontes.ccet.dcc.pg1.controller.AlunoController;
import br.unimontes.ccet.dcc.pg1.model.dao.exception.DAOException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Avell
 */
public class TelaCadastroAluno extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroAluno.class.getName());

    /**
     * Creates new form TelaCadastroAluno
     */
    public TelaCadastroAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPG11 = new br.unimontes.ccet.dcc.pg1.view.panels.PanelPG1();
        jlNome = new javax.swing.JLabel();
        jlCpf = new javax.swing.JLabel();
        jlDataNascimento = new javax.swing.JLabel();
        tfNome = new br.unimontes.ccet.dcc.pg1.view.components.TextFieldPG1();
        tfCpf = new br.unimontes.ccet.dcc.pg1.view.components.TextFieldPG1();
        tfDataNascimento = new br.unimontes.ccet.dcc.pg1.view.components.TextFieldPG1();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Aluno");
        setResizable(false);

        jlNome.setText("Nome");

        jlCpf.setText("CPF");

        jlDataNascimento.setText("Data Nascimento (YYYY-MM-DD)");

        tfNome.setName("tfNome"); // NOI18N

        tfCpf.setName("tfCpf"); // NOI18N

        tfDataNascimento.setName("tfDataNascimento"); // NOI18N

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPG11Layout = new javax.swing.GroupLayout(panelPG11);
        panelPG11.setLayout(panelPG11Layout);
        panelPG11Layout.setHorizontalGroup(
            panelPG11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPG11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPG11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPG11Layout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPG11Layout.createSequentialGroup()
                        .addComponent(jlCpf)
                        .addGap(18, 18, 18)
                        .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPG11Layout.createSequentialGroup()
                        .addComponent(jlDataNascimento)
                        .addGap(18, 18, 18)
                        .addComponent(tfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPG11Layout.createSequentialGroup()
                        .addComponent(jbCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLimpar)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelPG11Layout.setVerticalGroup(
            panelPG11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPG11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelPG11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(panelPG11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCpf)
                    .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPG11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDataNascimento)
                    .addComponent(tfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panelPG11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbLimpar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPG11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPG11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        try {
            String cpf = tfCpf.getText();
            String nome = tfNome.getText();
            String dataBr = tfDataNascimento.getText();
            
            AlunoController controller = new AlunoController();
            int resultado = controller.criar(cpf, nome, dataBr, "", "", "ativo");
            
            if(resultado > 0) {
                JOptionPane.showMessageDialog(this, "Aluno cadastrado com sucesso!");
                tfNome.setText("");
                tfCpf.setText("");
                tfDataNascimento.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Aluno não cadastrado!");
            }
        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Validação", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro de conexão: " + ex.getMessage(), "Erro BD", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {
        tfNome.setText("");
        tfCpf.setText("");
        tfDataNascimento.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroAluno().setVisible(true));
    }

    public void setAlunoFields(String cpf, String nome, String dataNascimento) {
        tfCpf.setText(cpf);
        tfNome.setText(nome);
        tfDataNascimento.setText(dataNascimento);
    }

    public void setCpfEditable(boolean editable) {
        tfCpf.setEditable(editable);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlDataNascimento;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlNome;
    private br.unimontes.ccet.dcc.pg1.view.panels.PanelPG1 panelPG11;
    private br.unimontes.ccet.dcc.pg1.view.components.TextFieldPG1 tfDataNascimento;
    private br.unimontes.ccet.dcc.pg1.view.components.TextFieldPG1 tfCpf;
    private br.unimontes.ccet.dcc.pg1.view.components.TextFieldPG1 tfNome;
    // End of variables declaration//GEN-END:variables
}
